### ISSUE TITLE
Not working with multiple Youtube video

### ISSUE THREAD

**Issue by bertrandmartel** [moay/afterglow#48]
I can't launch more than one Youtube video with `afterglow` class : 

```html
<video id="video1" class="afterglow" width="1920" height="1080" data-youtube-id="HgbHx4CY300"></video>
<video id="video2" class="afterglow" width="1920" height="1080" data-youtube-id="CaksNlNniis"></video>
```
fiddle : https://jsfiddle.net/bmartel/whf01e58/

Or is there another way ? 

Thanks for your help

**Comment by moay** [comment]
Should actually work, I'll look into it later.

**Comment by moay** [comment]
Seems to be a bug related to an api update. I don't have the time to fix this right now, but I'll look into it in some weeks.

**Comment by luckyrabbitllc** [comment]
I'm running into the same issue. Not sure why but this error shows up only when there are multiple instances on one page. A single instance works fine.

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://www.example.com').`

**Comment by moay** [comment]
Yeah, I got this one on the list. Currently, I just became father and I'm totally busy being just that. I'll look into it next year.

**Comment by kaptara** [comment]
Just replace line 42 in afterglow/vendor/videojs/plugins/Youtube.js with

`window.afterglow.ytIframeApiIncluded) || loadScript('https://www.youtube.com/iframe_api', apiLoaded);
window.afterglow.ytIframeApiIncluded = true;`

The problem is caused by multiple includes of the Youtube-IFRAME-API. This leads to an "no longer" initialized Youtube-Player, because it has been overwriten/reset by the API-Include for the succeeding video.

**Comment by moay** [comment]
Fixed in v2. Will come with the release.

**Comment by slavkaa** [comment]
Meet the same issue
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://www.example.com').

It looks like your demo not work`s as well http://docs.afterglowplayer.com/v1.1/docs/playing-a-youtube-video

**Comment by ViktorPika** [comment]
Same issue here, still not able to play multiple YouTube videos
